### PR TITLE
add lookup tables for ancient Greek and entry points

### PR DESCRIPTION
**Pull request by jmyerston**

### CODE REVIEW

**Comment by polm** [comment]
Thanks for this PR. I think we might need to think about how this affects the package size because it may run up against PyPI limits, but separate from that, could you fix the grc tests to use the new lemmas?

**Comment by adrianeboyd** [comment]
Ah, I think the problem is that there's not a spacy release with `grc` included yet, so the lemmatizer can't be initialized for testing. We'll rerun the tests after the next patch release.

**Comment by jmyerston** [comment]
Yes, I realized  that the test was not going to run after I created the PR.

In reality, the grc lemma file will be one of the smallest in the collection. I think only ro has a smaller size.  

The norm file could be reduced significantly if there is way to do the normalization by rules. For instance, all ὰ ὲ ὶ ὸ ὺ ὴ ὼ has to be normalized to ά έ ί, etc.  Using a table to do this is very inefficient, but I could not find other way to do it.

I will suggest accepting the lemmas for now, while I work on a rule based lemmatizer.

**Comment by adrianeboyd** [comment]
We're just extremely close to our current PyPI limit for this package and we don't have a particularly good argument for an increase, since data doesn't really belong in a package like this in the first place. Instead, we need to rework the config/loading possibilities to be able to easily load from URLs (which can still refer to this repo by default).

If a small amount of normalization would reduce the tables a lot, then it could make sense to implement a custom `lookup_lemmatize` method for `grc`. I know a few existing languages do this with common prefixes, Polish is one of them, I think?

**Comment by jmyerston** [comment]
I can reduce the lemma file, which is the largest (10mb).  grc_lexeme_norm is only 142 kb.  It will contain only the lemmas for training with the UD corpora. It will be on par with the model for stanza and it could go down to 1.2 mb without compression.  Does this work?

The lemma table will not be useful to improve models with prodigy, though. So the possibility of loading the data from an url will be very welcome. I imagine that people will want to add more languages as spacy and prodigy has become very popular.

**Comment by jmyerston** [comment]
I shortened the lemma table as much as I could.

**Comment by adrianeboyd** [comment]
If you think that the larger lookup table would be better, we can still include it in this repo.

We will just need to shift from loading tables from the `spacy-lookups-data` package to alternate loading methods for all languages because this isn't tenable in general.

**Comment by jmyerston** [comment]
Can we run the check again to see if the test works? It did not work last time because it required spacy 3.1.1.

**Comment by adrianeboyd** [comment]
Sure, we just need to adjust `requirements.txt` to use the right version of spacy for the tests.

**Comment by adrianeboyd** [comment]
I'll go ahead and merge this, but we'll still have to take a look at the final package size.

**Pull request merged**
