### PR TITLE
Add lookup tables for Italian by POS.

### PR DESCRIPTION
**Pull request by gtoffoli**
Includes also the new lookups.bin file, to be moved elsewhere.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Hi, thanks for your work on this! Could you add a file with the source and license information for this data similar to the `.txt` files for other languages? The filename `it_license.txt` would be fine.

**Comment by gtoffoli** [comment]
Hi Adriane, I've added the file with source and license information.

**Comment by adrianeboyd** [comment]
Thanks! I was worried it was only LGPL, which would make it incompatible with the `it_core_*` pipelines, but since it's dual-licensed as CC BY-SA, I think it should be fine to make it the default Italian lemmatizer for the pretrained pipelines.

We don't need the `lookups.bin` file in the repo, so it can be removed from the PR. The tests within this repo are mainly targeted at the lookup lemmas because the CI doesn't have pretrained pipelines test with taggers, so if we want to add tests for the POS-based lemmatizer and we end up using it in `it_core_*` pipelines, then a good place for a few tests would be `spacy-models`.

**Comment by francoishernandez** [comment]
Hi there,
Not sure if it's intended, but this seems to break loading of `it_core_news_sm` 2.3.0, with `spacy` 2.3.7. (Tested via `pip install spacy_lookups_data`, which fetches the latest 1.0.1 version.)

`ValueError: [E160] Can't find language data file: /usr/local/lib/python3.8/dist-packages/spacy_lookups_data/data/it_lemma_lookup_legacy.json.gz`

**Comment by adrianeboyd** [comment]
Thanks for the note, that's definitely not intended! I will yank v1.0.1 and prepare a new release to fix this...

**Comment by adrianeboyd** [comment]
Also as a note, I think that spacy v2.x may only be compatible with `spacy_lookups_data>=0.3.2,<0.4.0`, which is what is in the install extras with `pip install spacy[lookups]`. I am not entirely sure v1.0 will necessarily work with v2.x, but in any case, the error above is a bug that needs to be fixed for v3.x at least.

**Pull request merged**
