### PR TITLE
Add rules for verbs like "espiar" and "actuar"

### PR DESCRIPTION
**Pull request by nimbusaeta**
Adds rules to the whole indicative present paradigm, addresses issue https://github.com/explosion/spaCy/issues/11269

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Thanks for the PR! We'll double-check the performance internally and if everything looks fine, we'll merge this in preparation for the v3.5.0 `es` models.

**Comment by richardpaulhudson** [comment]
Hi @nimbusaeta, thanks for your commit. I've also added the third-person plural present subjunctive forms. Could you please check you agree these are linguistically correct, and if you're happy with them I'll approve the PR.

**Comment by nimbusaeta** [comment]
Hi @richardpaulhudson, sorry I missed that tense! They are totally correct.

**Comment by adrianeboyd** [comment]
Thanks for the feedback!

**Pull request merged**
